In [22]:
users = {
    "username" : "prasad",
    "age" : 24,
    "is_admin" : True
}

In [23]:
print(users)

{'username': 'prasad', 'age': 24, 'is_admin': True}


In [24]:
print(users.get("username")); print(users.get("age")); print(users.get("is_admin"))

prasad
24
True


In [25]:
users.pop("is_admin") #remove key
print(users)

{'username': 'prasad', 'age': 24}


In [26]:
users.update({"is_admin":True})
print(users)

{'username': 'prasad', 'age': 24, 'is_admin': True}


In [27]:
del users["is_admin"]
print(users)

{'username': 'prasad', 'age': 24}


In [28]:
print(len(users))

2


In [29]:
for x in users:
    print(x)

username
age


In [30]:
for x in users:
    print(f"{x}: {users[x]}") #print key and value

username: prasad
age: 24


In [3]:
import numpy as np 

In [7]:
data = np.array([23.3, 23, 36, 44, 43, 34, 48])

In [8]:
first_week = data[:8]
print(first_week)

[23.3 23.  36.  44.  43.  34.  48. ]


In [12]:
first_weeek = data[:8]
fourth_week = data[24:31]
print(first_week)

[23.3 23.  36.  44.  43.  34.  48. ]


In [13]:
data_above_30 = data[data > 30]
print(data_above_30)

[32.  31.  43.  32.3 32.  40.  39. ]


In [ ]:
arr_1 = np.array([10, 20, 10, 30, 11 , 78 , 88, 100 , 12, 12, 89, 69 ])

In [ ]:
print(arr_1.reshape(4,3))

[[ 10  20  10]
 [ 30  11  78]
 [ 88 100  12]
 [ 12  89  69]]


In [38]:
arr_1 = np.array([10, 20, 10, 30, 11 , 78 , 88, 100 , 12, 12, 89, 69 ])
arr_2 = arr_1 * 10
print(np.vstack((arr_1, arr_2)))


[[  10   20   10   30   11   78   88  100   12   12   89   69]
 [ 100  200  100  300  110  780  880 1000  120  120  890  690]]


In [39]:
arr_1.reshape(4,3).T

array([[ 10,  30,  88,  12],
       [ 20,  11, 100,  89],
       [ 10,  78,  12,  69]])

In [44]:
student_data = np.random.randint(10,20,(10,5))
print(student_data)

[[17 18 16 18 10]
 [12 17 13 13 15]
 [11 11 16 11 12]
 [16 10 16 10 11]
 [18 18 19 19 11]
 [16 11 13 10 15]
 [14 13 15 14 17]
 [11 10 16 14 14]
 [11 17 11 12 19]
 [15 10 15 18 12]]


In [ ]:
student_avg = student_data.mean(axis=1)
avg = np.mean(student_data, axis=1)
print(avg)

[15.8 14.  12.2 12.6 17.  13.  14.6 13.  14.  14. ]


In [50]:
subject_avg = student_data.mean(axis=0)
print(subject_avg)


[14.1 13.5 15.  13.9 13.6]


In [61]:
normal_age = np.random.normal(10,35,10)*1
print(normal_age)

[ 34.97357261  14.57892239  66.85902358  36.56049068  47.15509335
   3.19072231   9.18409307  16.2605635  -24.24049656  13.86679368]


In [62]:
uniform_age = np.random.uniform(10,31,10)*1
print(uniform_age)

[25.1567707  22.0350342  13.75938003 16.4503635  27.348179   25.56304465
 17.9246131  16.16565944 29.74959078 21.68756876]


In [67]:
customer_age = np.random.choice(normal_age, 10)
print(customer_age)

[ 16.2605635  -24.24049656  66.85902358  47.15509335  36.56049068
  66.85902358   3.19072231   9.18409307  13.86679368  34.97357261]


In [68]:
dice_roll = np.random.randint(1,7, 1000)
prob = np.where(dice_roll == 1) 
print(prob)

(array([ 20,  22,  27,  50,  51,  56,  62,  63,  65,  66,  69,  72,  76,
        80,  89,  99, 115, 128, 135, 137, 141, 145, 149, 152, 155, 156,
       157, 159, 161, 163, 165, 168, 182, 192, 213, 215, 218, 220, 222,
       229, 234, 243, 247, 252, 260, 265, 270, 288, 309, 327, 328, 335,
       339, 340, 364, 368, 389, 398, 403, 409, 411, 430, 431, 432, 437,
       438, 445, 446, 452, 460, 461, 469, 470, 475, 479, 480, 481, 494,
       497, 502, 504, 512, 520, 525, 528, 529, 530, 540, 556, 560, 561,
       563, 566, 572, 573, 574, 583, 584, 586, 587, 594, 603, 616, 621,
       630, 633, 642, 645, 651, 661, 664, 672, 685, 690, 693, 697, 700,
       704, 720, 723, 732, 734, 736, 738, 747, 750, 763, 764, 774, 784,
       786, 790, 791, 795, 802, 806, 833, 837, 848, 849, 856, 879, 883,
       885, 888, 889, 896, 904, 914, 916, 917, 919, 921, 927, 930, 931,
       950, 972, 976, 980, 983, 992, 995, 999]),)


In [70]:
sensor_reading = np.array([1,2, np.nan, 4, np.nan])
print(np.isnan(sensor_reading).sum())

2


In [82]:
filtered = np.isnan(sensor_reading)
print(~filtered)


[ True  True False  True False]


In [73]:
np.where(np.isnan(sensor_reading),np.nanmean(sensor_reading), sensor_reading)

array([1.        , 2.        , 2.33333333, 4.        , 2.33333333])